apiVersion: v1
kind: Pod
spec:
  containers:
  - env:
    image: jenkins/jnlp-slave
    imagePullPolicy: IfNotPresent
    name: jnlp
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      privileged: false