apiVersion: v1
kind: Service
metadata:
  name: "eid-validator"
  namespace: "dev"
spec:
  selector:
    app: "eid-validator"
    namepsace: "dev"
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP