apiVersion: v1
kind: Service
metadata:
  name: eid-validator-lb
  namespace: dev
spec:
  selector:
    app: eid-validator
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP