apiVersion: v1
kind: Pod
metadata:
  generateName: "true"
  labels:
    run: "eid-validator-dev"
  namespace: default
  resourceVersion: "246269"
spec:
  containers:
  - image: "124837307879.dkr.ecr.us-east-1.amazonaws.com/com.hero/eid-validator
    imagePullPolicy: Always
    name: "eid-validator-dev"