apiVersion: v1
kind: Pod
metadata:
  generateName: "eid-validator-"
  labels:
    run: "eid-validator-dev"
  namespace: default
spec:
  containers:
  - image: "124837307879.dkr.ecr.us-east-1.amazonaws.com/com.hero/eid"
    imagePullPolicy: Always
    name: "eid-validator-dev"
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "1Gi"