apiVersion: v1
kind: Pod
metadata:
  name: eid-validator
  namespace: dev
  labels:
    app: eid-validator
spec:
  containers:
  - image: 124837307879.dkr.ecr.us-east-1.amazonaws.com/com.hero/eid:latest
    imagePullPolicy: Always
    name: eid-validator
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "1Gi"
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP